version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - docker.env
    ports:
      - 8080:80
    depends_on:
      - postgres

volumes:
  postgres: